# Generated by Django 6.0.5 on 2026-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category"},
        ),
        migrations.AlterModelOptions(
            name="subtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Sub Task",
                "verbose_name_plural": "Sub Tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_category_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="subtask",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_sub_task_title"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("title",), name="unique_task_title"
            ),
        ),
        migrations.AlterModelTable(
            name="category",
            table="task_manager_category",
        ),
        migrations.AlterModelTable(
            name="subtask",
            table="task_manager_subtask",
        ),
        migrations.AlterModelTable(
            name="task",
            table="task_manager_task",
        ),
    ]
